'use client';

import { useMemo, useState, type ReactNode } from 'react';

import { ARTICLE_CONTENT_TYPES, ARTICLE_SCHEMA_TYPES, CONTENT_STATUSES, PAGE_SCHEMA_TYPES, PAGE_TEMPLATES, type ArticleRecord, type ContentKind, type ContentStatus, type ContentWorkspace, type PageRecord } from '../../lib/cms-types';
import { createSlug } from '../../lib/cms-validation';
import { FOOTER_GROUPS } from '../../data/required-pages';
import { AdminHeader } from './AdminHeader';
import { AdminImageField } from './AdminImageField';
import { ContentComposer } from './ContentComposer';

interface CmsResponse { error?: string; fieldErrors?: Record<string, string>; message?: string; warnings?: string[]; workspace?: ContentWorkspace; }
type EditableRecord = ArticleRecord | PageRecord;
interface FaqDraft { id: string; question: string; answer: string; category: string; displayOrder: number; enabled: boolean; }
interface Draft {
  id: string | null; title: string; slug: string; excerpt: string; body: string; featuredImage: string; featuredImagePrompt: string; status: ContentStatus; publishedAt: string; scheduledAt: string; authorName: string; featured: boolean; contentType: string; secondaryKeywords: string[]; pageTemplate: string; navigationLabel: string; showInNavigation: boolean; navigationOrder: number; enabled: boolean; requiredPageKey: string | null; showInFooter: boolean; footerLabel: string; footerOrder: number; footerGroup: string; faqEntries: FaqDraft[]; categoryIds: string[]; primaryCategoryId: string; tagIds: string[]; relatedArticleIds: string[]; seoTitle: string; metaDescription: string; canonicalUrl: string; openGraphTitle: string; openGraphDescription: string; openGraphImage: string; twitterTitle: string; twitterDescription: string; twitterImage: string; robotsIndex: boolean; robotsFollow: boolean; focusKeyword: string; schemaType: string; noindex: boolean;
}

export function ContentAdminDashboard({ kind, initialWorkspace, openCreateForm = false, initialEditId }: { kind: ContentKind; initialWorkspace: ContentWorkspace; openCreateForm?: boolean; initialEditId?: string }) {
  const [workspace, setWorkspace] = useState(initialWorkspace);
  const initialRecord = (kind === 'article' ? initialWorkspace.articles : initialWorkspace.pages).find((record) => record.id === initialEditId);
  const [editor, setEditor] = useState<Draft | null>(initialRecord ? fromRecord(initialRecord, kind) : openCreateForm ? emptyDraft(kind) : null);
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [category, setCategory] = useState('all'); const [tag, setTag] = useState('all'); const [sort, setSort] = useState('updated-desc');
  const records = kind === 'article' ? workspace.articles : workspace.pages;
  const visible = useMemo(() => records.filter((record) => {
    if (search && !`${record.title} ${record.slug} ${record.excerpt}`.toLowerCase().includes(search.toLowerCase())) return false;
    if (status !== 'all' && record.status !== status) return false;
    if (kind === 'article') { const article = record as ArticleRecord; if (category !== 'all' && !article.categories.some((item) => item.id === category)) return false; if (tag !== 'all' && !article.tags.some((item) => item.id === tag)) return false; }
    return true;
  }).sort((left, right) => compareRecords(left, right, sort)), [records, search, status, category, tag, sort, kind]);

  const request = async (url: string, method: 'POST' | 'PATCH' | 'DELETE', body?: unknown) => {
    setBusy(true); setError(''); setNotice(''); setFieldErrors({});
    try { const response = await fetch(url, { method, headers: body === undefined ? undefined : { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); const payload = await response.json() as CmsResponse; if (!response.ok) { setFieldErrors(payload.fieldErrors ?? {}); throw new Error(payload.error || 'The content request failed.'); } if (payload.workspace) setWorkspace(payload.workspace); setNotice([payload.message, ...(payload.warnings ?? [])].filter(Boolean).join(' ')); return true; }
    catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'The content request failed.'); return false; }
    finally { setBusy(false); }
  };

  const save = async (draft: Draft) => { const endpoint = `/api/admin/cms/${kind}s${draft.id ? `/${draft.id}` : ''}`; const saved = await request(endpoint, draft.id ? 'PATCH' : 'POST', toPayload(draft, kind)); if (saved) setEditor(null); };
  const perform = async (record: EditableRecord, action: 'duplicate' | 'delete' | 'unpublish' | 'publish' | 'move-up' | 'move-down') => {
    if (action === 'delete') { if (window.confirm(`Delete “${record.title}”? This cannot be undone.`)) await request(`/api/admin/cms/${kind}s/${record.id}`, 'DELETE'); return; }
    if (action === 'duplicate') { await request(`/api/admin/cms/${kind}s/${record.id}`, 'PATCH', { action: 'duplicate' }); return; }
    if (action === 'move-up' || action === 'move-down') { await request(`/api/admin/cms/pages/${record.id}`, 'PATCH', { action: 'move', direction: action === 'move-up' ? 'up' : 'down' }); return; }
    const draft = fromRecord(record, kind); draft.status = action === 'publish' ? 'published' : 'draft'; if (action === 'publish') draft.publishedAt = toLocalDateTime(new Date().toISOString()); await request(`/api/admin/cms/${kind}s/${record.id}`, 'PATCH', toPayload(draft, kind));
  };

  const label = kind === 'article' ? 'Articles' : 'Pages';
  return <main className="admin-theme min-h-screen px-4 py-8 text-slate-100 sm:px-6"><div className="mx-auto max-w-7xl"><AdminHeader active={kind === 'article' ? 'articles' : 'pages'} />
    <section className="rounded-3xl border border-white/10 bg-white/[0.04] p-5 sm:p-6">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-300">Content management</p><h1 className="mt-2 text-3xl font-black">{label}</h1><p className="mt-2 text-sm text-slate-400">Create, organize, preview, and publish SEO-ready {label.toLowerCase()}.</p></div><div className="flex flex-wrap gap-2">{kind === 'page' ? <button className={smallButton} disabled={busy} onClick={() => void request('/api/admin/cms/pages/restore', 'POST')} type="button">Restore required pages</button> : null}<button className={primaryButton} onClick={() => setEditor(emptyDraft(kind))} type="button">Create {kind}</button></div></div>
      {(notice || error) ? <Status error={error}>{error || notice}</Status> : null}
      <div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input aria-label={`Search ${label}`} className={inputClass} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${label.toLowerCase()}`} value={search} /><select className={inputClass} onChange={(event) => setStatus(event.target.value)} value={status}><option value="all">All statuses</option>{CONTENT_STATUSES.filter((item) => kind === 'article' || item !== 'scheduled').map((item) => <option key={item}>{item}</option>)}</select>{kind === 'article' ? <><select className={inputClass} onChange={(event) => setCategory(event.target.value)} value={category}><option value="all">All categories</option>{workspace.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={inputClass} onChange={(event) => setTag(event.target.value)} value={tag}><option value="all">All tags</option>{workspace.tags.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></> : null}<select className={inputClass} onChange={(event) => setSort(event.target.value)} value={sort}><option value="updated-desc">Recently updated</option><option value="created-desc">Recently created</option><option value="title-asc">Title A–Z</option><option value="publish-desc">Publish date</option></select></div>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">Title</th><th>Status</th><th>{kind === 'article' ? 'Category' : 'Navigation'}</th><th>Updated</th><th className="text-right">Actions</th></tr></thead><tbody>{visible.map((record, index) => <tr className="border-t border-white/10" key={record.id}><td className="p-3"><p className="font-black text-white">{record.title}</p><p className="text-xs text-slate-500">/{kind === 'article' ? 'articles' : 'pages'}/{record.slug}</p></td><td><StatusBadge status={record.status} /></td><td>{kind === 'article' ? ((record as ArticleRecord).categories.find((item) => item.isPrimary)?.name ?? '—') : ((record as PageRecord).showInNavigation ? (record as PageRecord).navigationLabel || record.title : 'Hidden')}</td><td>{formatDate(record.updatedAt)}</td><td><div className="flex justify-end gap-2"><button className={smallButton} onClick={() => setEditor(fromRecord(record, kind))} type="button">Edit</button><a className={smallButton} href={`/admin/preview/${kind}s/${record.id}`} rel="noreferrer" target="_blank">Preview</a><button className={smallButton} disabled={busy} onClick={() => void perform(record, 'duplicate')} type="button">Duplicate</button>{record.status === 'published' ? <button className={smallButton} onClick={() => void perform(record, 'unpublish')} type="button">Unpublish</button> : <button className={smallButton} onClick={() => void perform(record, 'publish')} type="button">Publish</button>}{kind === 'page' && (record as PageRecord).showInNavigation ? <><button aria-label="Move navigation page up" className={smallButton} disabled={index === 0} onClick={() => void perform(record, 'move-up')} type="button">↑</button><button aria-label="Move navigation page down" className={smallButton} disabled={index === visible.length - 1} onClick={() => void perform(record, 'move-down')} type="button">↓</button></> : null}<button className={dangerButton} onClick={() => void perform(record, 'delete')} type="button">Delete</button></div></td></tr>)}</tbody></table></div>
      {!visible.length ? <p className="mt-4 rounded-2xl border border-dashed border-white/10 p-8 text-center text-slate-500">No content matches these filters.</p> : null}
    </section></div>{editor ? <ContentEditor busy={busy} draft={editor} fieldErrors={fieldErrors} kind={kind} onChange={setEditor} onClose={() => setEditor(null)} onMediaChange={(media) => setWorkspace((current) => ({ ...current, media }))} onRestore={async (revisionId) => { if (!editor.id) return; const restored = await request(`/api/admin/cms/${kind}s/${editor.id}`, 'PATCH', { action: 'restore', revisionId }); if (restored) setEditor(null); }} onSave={save} workspace={workspace} /> : null}</main>;
}

function ContentEditor({ kind, draft, workspace, busy, fieldErrors, onChange, onMediaChange, onSave, onRestore, onClose }: { kind: ContentKind; draft: Draft; workspace: ContentWorkspace; busy: boolean; fieldErrors: Record<string, string>; onChange: (draft: Draft) => void; onMediaChange: (media: ContentWorkspace['media']) => void; onSave: (draft: Draft) => void; onRestore: (revisionId: string) => void; onClose: () => void }) {
  const original = kind === 'article' ? workspace.articles.find((item) => item.id === draft.id) : workspace.pages.find((item) => item.id === draft.id); const revisions = original?.revisions ?? [];
  const set = <K extends keyof Draft>(key: K, value: Draft[K]) => onChange({ ...draft, [key]: value });
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/80 p-3 backdrop-blur-sm"><div className="mx-auto my-4 max-w-6xl rounded-3xl border border-white/15 bg-[#0d111d] p-4 shadow-2xl sm:p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase text-violet-300">{draft.id ? 'Edit' : 'Create'} {kind}</p><h2 className="text-xl font-black">{draft.title || `Untitled ${kind}`}</h2></div><button className={smallButton} onClick={onClose} type="button">Close</button></div>{Object.keys(fieldErrors).length ? <Status error="Correct the highlighted fields.">Correct the highlighted fields.</Status> : null}
    <form className="mt-5 grid gap-5" onSubmit={(event) => { event.preventDefault(); onSave(draft); }}><div className="grid gap-4 lg:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><div className="grid gap-4">{kind === 'page' && draft.pageTemplate === 'legal' ? <aside className="rounded-2xl border border-amber-400/30 bg-amber-500/10 p-4 text-sm leading-6 text-amber-100"><strong>Admin legal review:</strong> This editable starter content is informational, not legal advice. Complete business identity and governing-law details and obtain qualified review before relying on it for launch.</aside> : null}<Field error={fieldErrors.title} label="Title"><input className={inputClass} onChange={(event) => { const title = event.target.value; onChange({ ...draft, title, slug: draft.slug && original ? draft.slug : createSlug(title) }); }} required value={draft.title} /></Field><Field error={fieldErrors.slug} label="Slug"><input className={inputClass} disabled={Boolean(draft.requiredPageKey)} onChange={(event) => set('slug', createSlug(event.target.value))} required value={draft.slug} />{draft.requiredPageKey ? <span className="text-xs text-slate-500">Required page URL: /{draft.requiredPageKey}</span> : original?.status === 'published' && original.slug !== draft.slug ? <span className="text-xs text-amber-300">Changing this published slug will create a 301 redirect.</span> : null}</Field><Field label="Subtitle / excerpt"><textarea className={`${inputClass} min-h-24`} maxLength={500} onChange={(event) => set('excerpt', event.target.value)} value={draft.excerpt} /></Field><ContentComposer body={draft.body} excerpt={draft.excerpt} featuredImage={draft.featuredImage} onChange={(body) => set('body', body)} onMediaChange={onMediaChange} title={draft.title} workspace={workspace} />{kind === 'page' && draft.pageTemplate === 'faq' ? <FaqEditor entries={draft.faqEntries} fieldErrors={fieldErrors} onChange={(faqEntries) => set('faqEntries', faqEntries)} /> : null}<SeoFields draft={draft} onChange={onChange} onMediaChange={onMediaChange} set={set} workspace={workspace} /></div>
      <aside className="grid content-start gap-4"><section className={panelClass}><h3 className="font-black">Publishing</h3><Field error={fieldErrors.status} label="Status"><select className={inputClass} onChange={(event) => set('status', event.target.value as ContentStatus)} value={draft.status}>{CONTENT_STATUSES.filter((item) => kind === 'article' || item !== 'scheduled').map((item) => <option key={item}>{item}</option>)}</select></Field>{kind === 'article' && draft.status === 'scheduled' ? <Field error={fieldErrors.scheduledAt} label="Schedule date"><input className={inputClass} onChange={(event) => set('scheduledAt', event.target.value)} type="datetime-local" value={draft.scheduledAt} /></Field> : null}<Field label="Published date"><input className={inputClass} onChange={(event) => set('publishedAt', event.target.value)} type="datetime-local" value={draft.publishedAt} /></Field><div className="grid grid-cols-2 gap-2"><button className={smallButton} disabled={busy} onClick={() => onSave({ ...draft, status: 'draft' })} type="button">Save Draft</button><button className={primaryButton} disabled={busy} onClick={() => onSave({ ...draft, status: 'published', publishedAt: draft.publishedAt || toLocalDateTime(new Date().toISOString()) })} type="button">Publish Now</button></div>{draft.id ? <a className={`${smallButton} text-center`} href={`/admin/preview/${kind}s/${draft.id}`} rel="noreferrer" target="_blank">Preview Draft</a> : null}</section>
      <section className={panelClass}><h3 className="font-black">Display</h3><AdminImageField folders={workspace.mediaFolders} label="Featured image" media={workspace.media} onChange={(value) => set('featuredImage', value)} onMediaChange={onMediaChange} value={draft.featuredImage} />{kind === 'article' ? <><Field label="Author"><input className={inputClass} onChange={(event) => set('authorName', event.target.value)} value={draft.authorName} /></Field><Field label="Content type"><select className={inputClass} onChange={(event) => set('contentType', event.target.value)} value={draft.contentType}>{ARTICLE_CONTENT_TYPES.map((item) => <option key={item}>{item}</option>)}</select></Field><Checkbox checked={draft.featured} label="Featured article" onChange={(value) => set('featured', value)} /></> : <><Checkbox checked={draft.enabled} label="Page enabled" onChange={(value) => set('enabled', value)} /><Field label="Page template"><select className={inputClass} onChange={(event) => set('pageTemplate', event.target.value)} value={draft.pageTemplate}>{PAGE_TEMPLATES.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Navigation label"><input className={inputClass} onChange={(event) => set('navigationLabel', event.target.value)} value={draft.navigationLabel} /></Field><Checkbox checked={draft.showInNavigation} label="Show in navigation" onChange={(value) => set('showInNavigation', value)} /><Field label="Navigation order"><input className={inputClass} min={0} onChange={(event) => set('navigationOrder', Number(event.target.value))} type="number" value={draft.navigationOrder} /></Field><hr className="border-white/10" /><Checkbox checked={draft.showInFooter} label="Show in footer" onChange={(value) => set('showInFooter', value)} /><Field label="Footer label"><input className={inputClass} onChange={(event) => set('footerLabel', event.target.value)} placeholder={draft.title || 'Page title'} value={draft.footerLabel} /></Field><Field error={fieldErrors.footerGroup} label="Footer group"><select className={inputClass} onChange={(event) => set('footerGroup', event.target.value)} value={draft.footerGroup}>{FOOTER_GROUPS.map((group) => <option key={group}>{group}</option>)}</select></Field><Field label="Footer order"><input className={inputClass} min={0} onChange={(event) => set('footerOrder', Number(event.target.value))} type="number" value={draft.footerOrder} /></Field></>}</section>
      {kind === 'article' ? <AiSeoMetadata draft={draft} set={set} /> : null}
      {kind === 'article' ? <ArticleOrganization draft={draft} onChange={onChange} set={set} workspace={workspace} /> : null}
      {revisions.length ? <section className={panelClass}><h3 className="font-black">Revisions</h3><div className="mt-3 grid max-h-64 gap-2 overflow-y-auto">{revisions.map((revision) => <details className="rounded-xl border border-white/10 p-3 text-xs" key={revision.id}><summary className="cursor-pointer font-bold">{formatDate(revision.createdAt)}</summary><p className="mt-2 font-bold text-white">{revision.titleSnapshot}</p><pre className="mt-2 max-h-28 overflow-auto whitespace-pre-wrap text-slate-500">{revision.bodySnapshot.slice(0, 600)}</pre><button className={`${smallButton} mt-2`} onClick={() => { if (window.confirm('Restore this revision? The current version will be saved first.')) onRestore(revision.id); }} type="button">Restore</button></details>)}</div></section> : null}
      <button className={primaryButton} disabled={busy} type="submit">{busy ? 'Saving…' : `Save ${kind}`}</button></aside></div></form></div></div>;
}

function AiSeoMetadata({ draft, set }: { draft: Draft; set: <K extends keyof Draft>(key: K, value: Draft[K]) => void }) {
  return <section className={panelClass}><h3 className="font-black">AI and SEO details</h3><Field label="Focus keyword"><input className={inputClass} onChange={(event) => set('focusKeyword', event.target.value)} value={draft.focusKeyword} /></Field><Field label="Secondary keywords"><input className={inputClass} onChange={(event) => set('secondaryKeywords', event.target.value.split(',').map((item) => item.trim()).filter(Boolean))} placeholder="keyword one, keyword two" value={draft.secondaryKeywords.join(', ')} /></Field><Field label="Featured image prompt"><textarea className={`${inputClass} min-h-28`} onChange={(event) => set('featuredImagePrompt', event.target.value)} placeholder="Saved image direction for the media workflow" value={draft.featuredImagePrompt} /></Field></section>;
}

function ArticleOrganization({ draft, onChange, set, workspace }: { draft: Draft; onChange: (draft: Draft) => void; set: <K extends keyof Draft>(key: K, value: Draft[K]) => void; workspace: ContentWorkspace }) {
  return <section className={panelClass}><h3 className="font-black">Organization</h3><Field label="Primary category"><select className={inputClass} onChange={(event) => { const id = event.target.value; onChange({ ...draft, primaryCategoryId: id, categoryIds: id && !draft.categoryIds.includes(id) ? [...draft.categoryIds, id] : draft.categoryIds }); }} value={draft.primaryCategoryId}><option value="">None</option>{workspace.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><div><p className="text-sm font-bold text-slate-300">Additional categories</p><div className="mt-2 grid gap-2">{workspace.categories.map((item) => <Checkbox checked={draft.categoryIds.includes(item.id)} key={item.id} label={item.name} onChange={(checked) => set('categoryIds', checked ? Array.from(new Set([...draft.categoryIds, item.id])) : draft.categoryIds.filter((id) => id !== item.id))} />)}</div></div><div><p className="text-sm font-bold text-slate-300">Tags</p><div className="mt-2 grid gap-2">{workspace.tags.map((item) => <Checkbox checked={draft.tagIds.includes(item.id)} key={item.id} label={item.name} onChange={(checked) => set('tagIds', checked ? [...draft.tagIds, item.id] : draft.tagIds.filter((id) => id !== item.id))} />)}</div></div><div><p className="text-sm font-bold text-slate-300">Manual related articles</p><div className="mt-2 grid max-h-48 gap-2 overflow-y-auto">{workspace.articles.filter((item) => item.id !== draft.id).map((item) => <Checkbox checked={draft.relatedArticleIds.includes(item.id)} key={item.id} label={item.title} onChange={(checked) => set('relatedArticleIds', checked ? [...draft.relatedArticleIds, item.id] : draft.relatedArticleIds.filter((id) => id !== item.id))} />)}</div></div></section>;
}

function FaqEditor({ entries, fieldErrors, onChange }: { entries: FaqDraft[]; fieldErrors: Record<string, string>; onChange: (entries: FaqDraft[]) => void }) {
  const update = (index: number, values: Partial<FaqDraft>) => onChange(entries.map((entry, entryIndex) => entryIndex === index ? { ...entry, ...values } : entry));
  const move = (index: number, direction: -1 | 1) => {
    const target = index + direction;
    if (target < 0 || target >= entries.length) return;
    const reordered = [...entries];
    [reordered[index], reordered[target]] = [reordered[target], reordered[index]];
    onChange(reordered.map((entry, entryIndex) => ({ ...entry, displayOrder: (entryIndex + 1) * 10 })));
  };
  return <section className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black text-white">FAQ entries</h3><p className="mt-1 text-xs text-slate-500">These structured entries power the public accordion, anchors, and FAQ schema.</p></div><button className={smallButton} onClick={() => onChange([...entries, { id: `new-${Date.now()}`, question: '', answer: '', category: 'General', displayOrder: (entries.length + 1) * 10, enabled: true }])} type="button">Add question</button></div><div className="mt-4 grid gap-3">{entries.map((entry, index) => <article className="rounded-2xl border border-white/10 bg-white/[0.03] p-4" key={entry.id}><div className="grid gap-3"><Field error={fieldErrors[`faqEntries.${index}.question`]} label={`Question ${index + 1}`}><input className={inputClass} onChange={(event) => update(index, { question: event.target.value })} value={entry.question} /></Field><Field error={fieldErrors[`faqEntries.${index}.answer`]} label="Answer"><textarea className={`${inputClass} min-h-28`} onChange={(event) => update(index, { answer: event.target.value })} value={entry.answer} /></Field><div className="grid gap-3 sm:grid-cols-[1fr_120px]"><Field label="Category"><input className={inputClass} onChange={(event) => update(index, { category: event.target.value })} value={entry.category} /></Field><Field label="Order"><input className={inputClass} min={0} onChange={(event) => update(index, { displayOrder: Number(event.target.value) })} type="number" value={entry.displayOrder} /></Field></div><div className="flex flex-wrap items-center gap-2"><Checkbox checked={entry.enabled} label="Enabled" onChange={(enabled) => update(index, { enabled })} /><button aria-label={`Move question ${index + 1} up`} className={smallButton} disabled={index === 0} onClick={() => move(index, -1)} type="button">Move up</button><button aria-label={`Move question ${index + 1} down`} className={smallButton} disabled={index === entries.length - 1} onClick={() => move(index, 1)} type="button">Move down</button><button className={dangerButton} onClick={() => onChange(entries.filter((_, entryIndex) => entryIndex !== index))} type="button">Remove</button></div></div></article>)}{!entries.length ? <p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">No FAQ entries yet.</p> : null}</div></section>;
}

function SeoFields({ draft, set, onChange, workspace, onMediaChange }: { draft: Draft; set: <K extends keyof Draft>(key: K, value: Draft[K]) => void; onChange: (draft: Draft) => void; workspace: ContentWorkspace; onMediaChange: (media: ContentWorkspace['media']) => void }) {
  return <details className={panelClass} open><summary className="cursor-pointer font-black">Search and social preview</summary><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label={`Meta title (${draft.seoTitle.length}/60)`}><input className={inputClass} onChange={(event) => set('seoTitle', event.target.value)} placeholder={draft.title || 'Search result title'} value={draft.seoTitle} /><LengthHint length={draft.seoTitle.length} max={65} min={40} target="50–60" /></Field><Field label={`Meta description (${draft.metaDescription.length}/160)`}><textarea className={`${inputClass} min-h-24`} onChange={(event) => set('metaDescription', event.target.value)} placeholder={draft.excerpt || 'Short search result summary'} value={draft.metaDescription} /><LengthHint length={draft.metaDescription.length} max={170} min={120} target="140–160" /></Field><Field label="Canonical URL"><input className={inputClass} onChange={(event) => set('canonicalUrl', event.target.value)} placeholder="https://example.com/articles/slug" value={draft.canonicalUrl} /></Field><Field label="Schema type"><select className={inputClass} onChange={(event) => set('schemaType', event.target.value)} value={draft.schemaType}>{[...ARTICLE_SCHEMA_TYPES, ...PAGE_SCHEMA_TYPES].filter((item, index, values) => values.indexOf(item) === index).map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Social share title"><input className={inputClass} onChange={(event) => set('openGraphTitle', event.target.value)} placeholder={draft.seoTitle || draft.title} value={draft.openGraphTitle} /></Field><Field label="Social share description"><textarea className={inputClass} onChange={(event) => set('openGraphDescription', event.target.value)} placeholder={draft.metaDescription || draft.excerpt} value={draft.openGraphDescription} /></Field><AdminImageField folders={workspace.mediaFolders} label="Social share image" media={workspace.media} onChange={(value) => set('openGraphImage', value)} onMediaChange={onMediaChange} value={draft.openGraphImage} /><div className="grid content-start gap-2 rounded-xl border border-white/10 p-3"><Checkbox checked={draft.robotsIndex && !draft.noindex} label="Allow search engines to index this content" onChange={(value) => onChange({ ...draft, robotsIndex: value, noindex: !value })} /><Checkbox checked={draft.robotsFollow} label="Allow search engines to follow links" onChange={(value) => set('robotsFollow', value)} /></div></div></details>;
}

function emptyDraft(kind: ContentKind): Draft { return { id: null, title: '', slug: '', excerpt: '', body: '', featuredImage: '', featuredImagePrompt: '', status: 'draft', publishedAt: '', scheduledAt: '', authorName: 'CanMyPCRunGTA6', featured: false, contentType: 'standard', secondaryKeywords: [], pageTemplate: 'standard', navigationLabel: '', showInNavigation: false, navigationOrder: 0, enabled: true, requiredPageKey: null, showInFooter: false, footerLabel: '', footerOrder: 0, footerGroup: 'Resources', faqEntries: [], categoryIds: [], primaryCategoryId: '', tagIds: [], relatedArticleIds: [], seoTitle: '', metaDescription: '', canonicalUrl: '', openGraphTitle: '', openGraphDescription: '', openGraphImage: '', twitterTitle: '', twitterDescription: '', twitterImage: '', robotsIndex: true, robotsFollow: true, focusKeyword: '', schemaType: kind === 'article' ? 'Article' : 'WebPage', noindex: false }; }
function fromRecord(record: EditableRecord, kind: ContentKind): Draft { const article = kind === 'article' ? record as ArticleRecord : null; const page = kind === 'page' ? record as PageRecord : null; return { ...emptyDraft(kind), ...record, id: record.id, featuredImage: record.featuredImage ?? '', featuredImagePrompt: article?.featuredImagePrompt ?? '', secondaryKeywords: article?.secondaryKeywords ?? [], publishedAt: toLocalDateTime(record.publishedAt), scheduledAt: article ? toLocalDateTime(article.scheduledAt) : '', authorName: article?.authorName ?? 'CanMyPCRunGTA6', featured: article?.featured ?? false, contentType: article?.contentType ?? 'standard', pageTemplate: page?.pageTemplate ?? 'standard', navigationLabel: page?.navigationLabel ?? '', showInNavigation: page?.showInNavigation ?? false, navigationOrder: page?.navigationOrder ?? 0, enabled: page?.enabled ?? true, requiredPageKey: page?.requiredPageKey ?? null, showInFooter: page?.showInFooter ?? false, footerLabel: page?.footerLabel ?? '', footerOrder: page?.footerOrder ?? 0, footerGroup: page?.footerGroup ?? 'Resources', faqEntries: page?.faqEntries.map((entry) => ({ ...entry })) ?? [], categoryIds: article?.categories.map((item) => item.id) ?? [], primaryCategoryId: article?.categories.find((item) => item.isPrimary)?.id ?? '', tagIds: article?.tags.map((item) => item.id) ?? [], relatedArticleIds: article?.relatedArticleIds ?? [], canonicalUrl: record.canonicalUrl ?? '', openGraphImage: record.openGraphImage ?? '', twitterImage: record.twitterImage ?? '' }; }
function toPayload(draft: Draft, kind: ContentKind) { const common = { title: draft.title, slug: draft.slug, excerpt: draft.excerpt, body: draft.body, featuredImage: draft.featuredImage || null, status: draft.status, publishedAt: dateIso(draft.publishedAt), seoTitle: draft.seoTitle, metaDescription: draft.metaDescription, canonicalUrl: draft.canonicalUrl || null, openGraphTitle: draft.openGraphTitle, openGraphDescription: draft.openGraphDescription, openGraphImage: draft.openGraphImage || null, twitterTitle: draft.twitterTitle, twitterDescription: draft.twitterDescription, twitterImage: draft.twitterImage || null, robotsIndex: draft.robotsIndex, robotsFollow: draft.robotsFollow, focusKeyword: draft.focusKeyword, schemaType: draft.schemaType, noindex: draft.noindex }; return kind === 'article' ? { ...common, featuredImagePrompt: draft.featuredImagePrompt, secondaryKeywords: draft.secondaryKeywords, authorName: draft.authorName, scheduledAt: dateIso(draft.scheduledAt), featured: draft.featured, contentType: draft.contentType, categoryIds: draft.categoryIds, primaryCategoryId: draft.primaryCategoryId || null, tagIds: draft.tagIds, relatedArticleIds: draft.relatedArticleIds } : { ...common, pageTemplate: draft.pageTemplate, navigationLabel: draft.navigationLabel, showInNavigation: draft.showInNavigation, navigationOrder: draft.navigationOrder, enabled: draft.enabled, showInFooter: draft.showInFooter, footerLabel: draft.footerLabel, footerOrder: draft.footerOrder, footerGroup: draft.footerGroup, faqEntries: draft.faqEntries }; }
function compareRecords(left: EditableRecord, right: EditableRecord, sort: string) { if (sort === 'title-asc') return left.title.localeCompare(right.title); if (sort === 'created-desc') return right.createdAt.localeCompare(left.createdAt); if (sort === 'publish-desc') return (right.publishedAt ?? '').localeCompare(left.publishedAt ?? ''); return right.updatedAt.localeCompare(left.updatedAt); }
function toLocalDateTime(value: string | null) { if (!value) return ''; const date = new Date(value); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }
function dateIso(value: string) { if (!value) return null; const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date.toISOString(); }
function formatDate(value: string) { return new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(new Date(value)); }
function StatusBadge({ status }: { status: ContentStatus }) { const styles = status === 'published' ? 'bg-emerald-500/15 text-emerald-300' : status === 'scheduled' ? 'bg-amber-500/15 text-amber-300' : status === 'archived' ? 'bg-slate-500/15 text-slate-400' : 'bg-violet-500/15 text-violet-300'; return <span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${styles}`}>{status}</span>; }
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="grid gap-2 text-sm font-bold text-slate-300"><span>{label}</span>{children}{error ? <span className="text-xs text-red-300">{error}</span> : null}</label>; }
function Checkbox({ checked, label, onChange }: { checked: boolean; label: string; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-2 text-sm text-slate-300"><input checked={checked} className="size-4 accent-violet-500" onChange={(event) => onChange(event.target.checked)} type="checkbox" />{label}</label>; }
function LengthHint({ length, min, max, target }: { length: number; min: number; max: number; target: string }) { return length && (length < min || length > max) ? <span className="text-xs text-amber-300">Usually performs best around {target} characters.</span> : <span className="text-xs text-slate-600">Target: {target} characters.</span>; }
function Status({ children, error }: { children: ReactNode; error?: string }) { return <p aria-live="polite" className={`mt-4 rounded-xl border px-3 py-2 text-sm ${error ? 'border-red-400/30 bg-red-500/10 text-red-200' : 'border-emerald-400/30 bg-emerald-500/10 text-emerald-200'}`}>{children}</p>; }
const inputClass = 'w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none placeholder:text-slate-600 focus:border-violet-400/60';
const panelClass = 'rounded-2xl border border-white/10 bg-black/20 p-4 grid gap-4';
const primaryButton = 'rounded-xl bg-violet-500 px-4 py-2.5 text-sm font-black text-white hover:bg-violet-400 disabled:opacity-50';
const smallButton = 'rounded-xl border border-white/15 bg-white/5 px-3 py-2 text-xs font-bold text-slate-200 hover:bg-white/10 disabled:opacity-40';
const dangerButton = 'rounded-xl border border-red-400/20 bg-red-500/10 px-3 py-2 text-xs font-bold text-red-200 hover:bg-red-500/20';
