'use client';

/* eslint-disable @next/next/no-img-element -- Media-library URLs use the configured runtime provider. */

import { useMemo, useState, type FormEvent } from 'react';
import type { MediaAssetRecord } from '../../lib/cms-types';
import { AdminHeader } from './AdminHeader';

interface MediaResponse { error?: string; message?: string; items?: MediaAssetRecord[]; }
export function MediaAdminDashboard({ initialItems }: { initialItems: MediaAssetRecord[] }) {
  const [items, setItems] = useState(initialItems); const [search, setSearch] = useState(''); const [file, setFile] = useState<File | null>(null); const [altText, setAltText] = useState(''); const [title, setTitle] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const visible = useMemo(() => items.filter((item) => `${item.filename} ${item.title} ${item.altText}`.toLowerCase().includes(search.toLowerCase())), [items, search]);
  const upload = async (event: FormEvent) => { event.preventDefault(); if (!file) return; setBusy(true); setError(''); setNotice(''); try { const form = new FormData(); form.set('file', file); form.set('altText', altText); form.set('title', title); const response = await fetch('/api/admin/cms/media', { method: 'POST', body: form }); const payload = await response.json() as MediaResponse; if (!response.ok) throw new Error(payload.error || 'Upload failed.'); if (payload.items) setItems(payload.items); setNotice(payload.message ?? 'Uploaded.'); setFile(null); setAltText(''); setTitle(''); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Upload failed.'); } finally { setBusy(false); } };
  const request = async (id: string, method: 'PATCH' | 'DELETE', body?: unknown) => { setBusy(true); setError(''); setNotice(''); try { const response = await fetch(`/api/admin/cms/media/${id}`, { method, headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json() as MediaResponse; if (!response.ok) throw new Error(payload.error || 'Media request failed.'); if (payload.items) setItems(payload.items); setNotice(payload.message ?? 'Saved.'); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Media request failed.'); } finally { setBusy(false); } };
  return <main className="admin-theme min-h-screen px-4 py-8 text-slate-100 sm:px-6"><div className="mx-auto max-w-7xl"><AdminHeader active="media" /><section className="rounded-3xl border border-white/10 bg-white/[0.04] p-5 sm:p-6"><div><p className="text-xs font-black uppercase tracking-wider text-violet-300">Content assets</p><h1 className="mt-2 text-3xl font-black">Media Library</h1><p className="mt-2 text-sm text-slate-400">Local uploads are for development. Configure a persistent storage adapter before production uploads.</p></div>{notice || error ? <p className={`mt-4 rounded-xl border p-3 text-sm ${error ? 'border-red-400/30 bg-red-500/10 text-red-200' : 'border-emerald-400/30 bg-emerald-500/10 text-emerald-200'}`}>{error || notice}</p> : null}<form className="mt-5 grid gap-3 rounded-2xl border border-white/10 bg-black/20 p-4 md:grid-cols-4" onSubmit={upload}><label className="grid gap-2 text-sm font-bold">Image<input accept="image/jpeg,image/png,image/gif,image/webp" className={inputClass} onChange={(event) => setFile(event.target.files?.[0] ?? null)} required type="file" /></label><label className="grid gap-2 text-sm font-bold">Alt text<input className={inputClass} onChange={(event) => setAltText(event.target.value)} value={altText} /></label><label className="grid gap-2 text-sm font-bold">Title<input className={inputClass} onChange={(event) => setTitle(event.target.value)} value={title} /></label><button className="self-end rounded-xl bg-violet-500 px-4 py-2.5 text-sm font-black" disabled={busy} type="submit">{busy ? 'Uploading…' : 'Upload image'}</button></form><input aria-label="Search media" className={`${inputClass} mt-5 max-w-lg`} onChange={(event) => setSearch(event.target.value)} placeholder="Search filename, title, or alt text" value={search} /><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visible.map((item) => <MediaCard busy={busy} item={item} key={item.id} onDelete={() => { if (window.confirm(`Delete unused image “${item.filename}”?`)) void request(item.id, 'DELETE'); }} onSave={(body) => void request(item.id, 'PATCH', body)} />)}</div></section></div></main>;
}
function MediaCard({ item, busy, onSave, onDelete }: { item: MediaAssetRecord; busy: boolean; onSave: (body: { altText: string; title: string }) => void; onDelete: () => void }) { const [altText, setAltText] = useState(item.altText); const [title, setTitle] = useState(item.title); return <article className="flex flex-col rounded-2xl border border-white/10 bg-black/20 p-3"><img alt={item.altText} className="aspect-video w-full rounded-xl bg-black/30 object-contain" src={item.url} /><p className="mt-3 truncate text-sm font-black">{item.filename}</p><p className="text-xs text-slate-500">{item.width && item.height ? `${item.width}×${item.height} · ` : ''}{formatBytes(item.fileSize)} · used {item.usageCount}×</p><label className="mt-3 grid gap-1 text-xs font-bold">Alt text<input className={inputClass} onChange={(event) => setAltText(event.target.value)} value={altText} /></label><label className="mt-2 grid gap-1 text-xs font-bold">Title<input className={inputClass} onChange={(event) => setTitle(event.target.value)} value={title} /></label><div className="mt-auto flex flex-wrap gap-2 pt-3"><button className={smallButton} disabled={busy} onClick={() => onSave({ altText, title })} type="button">Save</button><button className={smallButton} onClick={() => void navigator.clipboard.writeText(`${window.location.origin}${item.url}`)} type="button">Copy URL</button><button className={dangerButton} disabled={busy || item.usageCount > 0} onClick={onDelete} type="button">Delete</button></div></article>; }
function formatBytes(value: number) { return value > 1024 * 1024 ? `${(value / 1024 / 1024).toFixed(1)} MB` : `${Math.ceil(value / 1024)} KB`; }
const inputClass = 'w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none focus:border-violet-400/60'; const smallButton = 'rounded-xl border border-white/15 bg-white/5 px-3 py-2 text-xs font-bold'; const dangerButton = 'rounded-xl border border-red-400/20 bg-red-500/10 px-3 py-2 text-xs font-bold text-red-200 disabled:opacity-30';
