'use client';

import { useMemo, useState } from 'react';
import type { ContentCategoryRecord, ContentTagRecord } from '../../lib/cms-types';
import { createSlug } from '../../lib/cms-validation';
import { AdminHeader } from './AdminHeader';

type Item = ContentCategoryRecord | ContentTagRecord;
interface ResponseData { error?: string; message?: string; items?: Item[]; }

export function TaxonomyAdminDashboard({ kind, initialItems }: { kind: 'category' | 'tag'; initialItems: Item[] }) {
  const [items, setItems] = useState(initialItems); const [editor, setEditor] = useState<Item | 'new' | null>(null); const [search, setSearch] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const visible = useMemo(() => items.filter((item) => `${item.name} ${item.slug}`.toLowerCase().includes(search.toLowerCase())), [items, search]); const plural = kind === 'category' ? 'categories' : 'tags';
  const request = async (url: string, method: 'POST' | 'PATCH' | 'DELETE', body?: unknown) => { setBusy(true); setError(''); setNotice(''); try { const response = await fetch(url, { method, headers: body === undefined ? undefined : { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); const payload = await response.json() as ResponseData; if (!response.ok) throw new Error(payload.error || 'The taxonomy request failed.'); if (payload.items) setItems(payload.items); setNotice(payload.message ?? 'Saved.'); return true; } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'The taxonomy request failed.'); return false; } finally { setBusy(false); } };
  return <main className="admin-theme min-h-screen px-4 py-8 text-slate-100 sm:px-6"><div className="mx-auto max-w-6xl"><AdminHeader active={plural} /><section className="rounded-3xl border border-white/10 bg-white/[0.04] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-violet-300">Content organization</p><h1 className="mt-2 text-3xl font-black capitalize">{plural}</h1></div><button className={primaryButton} onClick={() => setEditor('new')} type="button">Create {kind}</button></div>{notice || error ? <Status error={error}>{error || notice}</Status> : null}<input aria-label={`Search ${plural}`} className={`${inputClass} mt-5 max-w-lg`} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${plural}`} value={search} /><div className="mt-5 grid gap-3">{visible.map((item, index) => <article className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 bg-black/20 p-4" key={item.id}><div><p className="font-black">{item.name}</p><p className="text-xs text-slate-500">/{kind === 'category' ? 'category' : 'tag'}/{item.slug} · {item.articleCount} article{item.articleCount === 1 ? '' : 's'}</p></div><div className="flex flex-wrap gap-2">{kind === 'category' ? <><button className={smallButton} disabled={index === 0 || busy} onClick={() => void request(`/api/admin/cms/categories/${item.id}`, 'PATCH', { action: 'move', direction: 'up' })} type="button">↑</button><button className={smallButton} disabled={index === visible.length - 1 || busy} onClick={() => void request(`/api/admin/cms/categories/${item.id}`, 'PATCH', { action: 'move', direction: 'down' })} type="button">↓</button></> : null}<button className={smallButton} onClick={() => setEditor(item)} type="button">Edit</button><MergeButton busy={busy} item={item} items={items} kind={kind} request={request} /><button className={dangerButton} disabled={busy || item.articleCount > 0} onClick={() => { if (window.confirm(`Delete unused ${kind} “${item.name}”?`)) void request(`/api/admin/cms/${plural}/${item.id}`, 'DELETE'); }} title={item.articleCount ? 'Merge or remove article links first' : ''} type="button">Delete</button></div></article>)}</div></section></div>{editor ? <TaxonomyEditor item={editor === 'new' ? null : editor} kind={kind} busy={busy} error={error} onClose={() => setEditor(null)} onSave={async (body) => { const id = editor === 'new' ? null : editor.id; if (await request(`/api/admin/cms/${plural}${id ? `/${id}` : ''}`, id ? 'PATCH' : 'POST', body)) setEditor(null); }} /> : null}</main>;
}

function TaxonomyEditor({ item, kind, busy, error, onClose, onSave }: { item: Item | null; kind: 'category' | 'tag'; busy: boolean; error: string; onClose: () => void; onSave: (body: Record<string, unknown>) => void }) { const category = item && 'description' in item ? item : null; const [name, setName] = useState(item?.name ?? ''); const [slug, setSlug] = useState(item?.slug ?? ''); const [description, setDescription] = useState(category?.description ?? ''); const [imageUrl, setImageUrl] = useState(category?.imageUrl ?? ''); const [seoTitle, setSeoTitle] = useState(category?.seoTitle ?? ''); const [metaDescription, setMetaDescription] = useState(category?.metaDescription ?? ''); return <Modal title={`${item ? 'Edit' : 'Create'} ${kind}`} onClose={onClose}>{error ? <Status error={error}>{error}</Status> : null}<form className="mt-4 grid gap-4" onSubmit={(event) => { event.preventDefault(); onSave({ name, slug, description, imageUrl: imageUrl || null, seoTitle, metaDescription }); }}><Field label="Name"><input className={inputClass} onChange={(event) => { setName(event.target.value); if (!item) setSlug(createSlug(event.target.value)); }} required value={name} /></Field><Field label="Slug"><input className={inputClass} onChange={(event) => setSlug(createSlug(event.target.value))} required value={slug} /></Field>{kind === 'category' ? <><Field label="Description"><textarea className={`${inputClass} min-h-24`} onChange={(event) => setDescription(event.target.value)} value={description} /></Field><Field label="Category image"><input className={inputClass} onChange={(event) => setImageUrl(event.target.value)} value={imageUrl} /></Field><Field label={`SEO title (${seoTitle.length})`}><input className={inputClass} onChange={(event) => setSeoTitle(event.target.value)} value={seoTitle} /></Field><Field label={`Meta description (${metaDescription.length})`}><textarea className={inputClass} onChange={(event) => setMetaDescription(event.target.value)} value={metaDescription} /></Field></> : null}<button className={primaryButton} disabled={busy} type="submit">{busy ? 'Saving…' : `Save ${kind}`}</button></form></Modal>; }
function MergeButton({ item, items, kind, busy, request }: { item: Item; items: Item[]; kind: 'category' | 'tag'; busy: boolean; request: (url: string, method: 'POST' | 'PATCH' | 'DELETE', body?: unknown) => Promise<boolean> }) { const plural = kind === 'category' ? 'categories' : 'tags'; return <select aria-label={`Merge ${item.name} into`} className={smallButton} disabled={busy || items.length < 2} onChange={(event) => { const targetId = event.target.value; if (targetId && window.confirm(`Merge “${item.name}” into the selected ${kind}?`)) void request(`/api/admin/cms/${plural}/${item.id}`, 'PATCH', { action: 'merge', targetId }); event.target.value = ''; }} defaultValue=""><option value="">Merge into…</option>{items.filter((target) => target.id !== item.id).map((target) => <option key={target.id} value={target.id}>{target.name}</option>)}</select>; }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/80 p-4"><div className="mx-auto my-8 max-w-xl rounded-3xl border border-white/15 bg-[#0d111d] p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2><button className={smallButton} onClick={onClose} type="button">Close</button></div>{children}</div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-bold text-slate-300"><span>{label}</span>{children}</label>; }
function Status({ children, error }: { children: React.ReactNode; error?: string }) { return <p className={`mt-4 rounded-xl border p-3 text-sm ${error ? 'border-red-400/30 bg-red-500/10 text-red-200' : 'border-emerald-400/30 bg-emerald-500/10 text-emerald-200'}`}>{children}</p>; }
const inputClass = 'w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none focus:border-violet-400/60'; const primaryButton = 'rounded-xl bg-violet-500 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50'; const smallButton = 'rounded-xl border border-white/15 bg-white/5 px-3 py-2 text-xs font-bold text-slate-200 disabled:opacity-40'; const dangerButton = 'rounded-xl border border-red-400/20 bg-red-500/10 px-3 py-2 text-xs font-bold text-red-200 disabled:opacity-30';
